/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xyz;

import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jdk.nashorn.internal.parser.TokenType;

/**
 *
 * @author USER-PC
 */
public class ProductionManagerPlatForm extends javax.swing.JFrame {

    /**
     * Creates new form ProductionManagerPlatForm
     */
     public Connection conn = null;
    public Statement stmt = null;
    public String sql = "";
    public ProductionManagerPlatForm() {
        initComponents();
        this.setLocationRelativeTo(null);//jframe center
        conn = dbconnection.getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblMeal = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dateForPm = new com.toedter.calendar.JDateChooser();
        cmbUnitForPm = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        lblDamage = new javax.swing.JLabel();
        lblProductionEfficiency1 = new javax.swing.JLabel();
        lblFinal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnPmShow = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableForPm = new javax.swing.JTable();
        btnPmView = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/xyz/back.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Damage Precentage");

        lblMeal.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblMeal.setForeground(new java.awt.Color(0, 0, 102));
        lblMeal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMeal.setText(".");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Unit Name");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Meal Expences");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Final Status");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Production Efficiency");

        cmbUnitForPm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Print Unit", "Handle Unit", "Cutting Unit", "Bordering Unit", "Tailoring Unit", "Complete Unit" }));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Date");

        lblDamage.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblDamage.setForeground(new java.awt.Color(0, 0, 102));
        lblDamage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDamage.setText(".");

        lblProductionEfficiency1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblProductionEfficiency1.setForeground(new java.awt.Color(0, 0, 102));
        lblProductionEfficiency1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblProductionEfficiency1.setText(".");

        lblFinal.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblFinal.setForeground(new java.awt.Color(0, 0, 102));
        lblFinal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFinal.setText(".");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Analystics Details Of Each Unit");

        btnPmShow.setBackground(new java.awt.Color(255, 255, 204));
        btnPmShow.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnPmShow.setForeground(new java.awt.Color(0, 0, 102));
        btnPmShow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/xyz/analys.png"))); // NOI18N
        btnPmShow.setText("Show Report");
        btnPmShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPmShowActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("Warning!! if you need to Show Report Please Enter UnitName and Relevant Date");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPmShow, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(cmbUnitForPm, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel6))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDamage, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dateForPm, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel7))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(341, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(197, 197, 197)
                    .addComponent(lblProductionEfficiency1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(292, 292, 292)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(145, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(dateForPm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbUnitForPm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDamage, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnPmShow)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(122, 122, 122)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(451, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(265, 265, 265)
                    .addComponent(lblProductionEfficiency1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(308, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(56, 56, 56)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(517, Short.MAX_VALUE)))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Production Table");

        TableForPm.setBackground(new java.awt.Color(255, 255, 204));
        TableForPm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Unit_Name", "Supervisor_Id", "Present_Employee", "Absance_Employee", "Total_Production", "Damage_Count"
            }
        ));
        jScrollPane1.setViewportView(TableForPm);

        btnPmView.setBackground(new java.awt.Color(255, 255, 204));
        btnPmView.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnPmView.setForeground(new java.awt.Color(0, 0, 102));
        btnPmView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/xyz/view2.png"))); // NOI18N
        btnPmView.setText("View");
        btnPmView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPmViewActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 204));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 0, 153));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/xyz/analys2.png"))); // NOI18N
        jButton2.setText("Create Text Report");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPmView, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPmView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        productionmanagerlog obj=new productionmanagerlog();
        this.setVisible(false);
        obj.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnPmViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPmViewActionPerformed
         try {
            stmt=conn.createStatement();
            sql="select*from production";
            ResultSet rs=stmt.executeQuery(sql);
            while(rs.next())
            {
                String date=rs.getString("date");
                String unit=rs.getString("unit_name");
                String supid=rs.getString("supervisor_id");
                String PresentEmployee=String.valueOf(rs.getInt("present_employee"));
                String AbsanceEmployee=String.valueOf(rs.getInt("absance_employee"));
                String TotalProduction=String.valueOf(rs.getInt("total_production"));
                String DamageCount=String.valueOf(rs.getInt("damage_count"));
                
                
                String tbdata[]={date,unit,supid,PresentEmployee,AbsanceEmployee,TotalProduction,DamageCount};
                DefaultTableModel tblModel=(DefaultTableModel)TableForPm.getModel();
                tblModel.addRow(tbdata);
                
            
            
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnPmViewActionPerformed

    private void btnPmShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPmShowActionPerformed
          SimpleDateFormat sdf;
         sdf = new SimpleDateFormat("yyyy-MM-dd");
        String date=sdf.format(dateForPm.getDate());
        System.out.println(date);
        String unit=(String) cmbUnitForPm.getSelectedItem();
        
        try {
            stmt=conn.createStatement();
            sql="select * from production where date='"+date+"'and unit_name='"+cmbUnitForPm.getSelectedItem()+"'";
            ResultSet rs=stmt.executeQuery(sql);
            
            while(rs.next())
            {
              int presentemployee=Integer.parseInt(rs.getString("present_employee"));
               int absanceemployee=Integer.parseInt(rs.getString("absance_employee"));
                int totalproduction=Integer.parseInt(rs.getString("total_production"));
                 int damagecount=Integer.parseInt(rs.getString("damage_count"));
             
                 
                 System.out.println(presentemployee);
                 if("Print Unit"==cmbUnitForPm.getSelectedItem())
                 {
                    float totalMeal=((presentemployee*100)+(presentemployee*150)+(presentemployee*50*20));
                    float productionefficiency=(totalproduction*100)/1500;
                    float damageprecentage=(damagecount*100)/totalproduction;
                    
                    
                     
                     lblMeal.setText("Rs."+totalMeal+ " ");
                     lblProductionEfficiency1.setText(productionefficiency+""+"%");
                     lblDamage.setText(damageprecentage+""+"%");
                     
                     if(productionefficiency>=85 && damageprecentage<=10)
                     {
                     
                        lblFinal.setText("GREAT");
                     
                     }
                     else if(productionefficiency<85 && productionefficiency>=65 && damageprecentage>10 && damageprecentage<=20)
                     {
                        lblFinal.setText("GOOD");
                     
                     }
                     else
                     {
                        lblFinal.setText("INDICATING HIGH RSIK FOR FAINANCIAL HEALTH");
                     
                     }                 
                 
                 }
                 else if("Handle Unit"==cmbUnitForPm.getSelectedItem())
                 {
                     float totalMeal=((presentemployee*100)+(presentemployee*150)+(presentemployee*50*20));
                    float productionefficiency=(totalproduction*100)/1000;
                    float damageprecentage=(damagecount*100)/totalproduction;
                    
                    
                     
                     lblMeal.setText("Rs."+totalMeal+ " ");
                     lblProductionEfficiency1.setText(productionefficiency+""+"%");
                     lblDamage.setText(damageprecentage+""+"%");
                     
                     if(productionefficiency>=85 && damageprecentage<=10)
                     {
                     
                        lblFinal.setText("GREAT");
                     
                     }
                     else if(productionefficiency<85 && productionefficiency>=65 && damageprecentage>10 && damageprecentage<=20)
                     {
                        lblFinal.setText("GOOD");
                     
                     }
                     else
                     {
                        lblFinal.setText("INDICATING HIGH RSIK FOR FAINANCIAL HEALTH");
                     
                     }                 
                 
                 
                 }
                 else if("Cutting Unit"==cmbUnitForPm.getSelectedItem())
                 {
                     
                     float totalMeal=((presentemployee*100)+(presentemployee*150)+(presentemployee*50*20));
                    float productionefficiency=(totalproduction*100)/1200;
                    float damageprecentage=(damagecount*100)/totalproduction;
                    
                    
                     
                     lblMeal.setText("Rs."+totalMeal+ " ");
                     lblProductionEfficiency1.setText(productionefficiency+""+"%");
                     lblDamage.setText(damageprecentage+""+"%");
                     
                     if(productionefficiency>=85 && damageprecentage<=10)
                     {
                     
                        lblFinal.setText("GREAT");
                     
                     }
                     else if(productionefficiency<85 && productionefficiency>=65 && damageprecentage>10 && damageprecentage<=20)
                     {
                        lblFinal.setText("GOOD");
                     
                     }
                     else
                     {
                        lblFinal.setText("INDICATING HIGH RSIK FOR FAINANCIAL HEALTH");
                     
                     }                 
                 
                 
                 
                 }
                 else if("Bordering Unit"==cmbUnitForPm.getSelectedItem())
                 {
                     float totalMeal=((presentemployee*100)+(presentemployee*150)+(presentemployee*50*20));
                    float productionefficiency=(totalproduction*100)/1500;
                    float damageprecentage=(damagecount*100)/totalproduction;
                    
                    
                     
                     lblMeal.setText("Rs."+totalMeal+ " ");
                     lblProductionEfficiency1.setText(productionefficiency+""+"%");
                     lblDamage.setText(damageprecentage+""+"%");
                     
                     if(productionefficiency>=85 && damageprecentage<=10)
                     {
                     
                        lblFinal.setText("GREAT");
                     
                     }
                     else if(productionefficiency<85 && productionefficiency>=65 && damageprecentage>10 && damageprecentage<=20)
                     {
                        lblFinal.setText("GOOD");
                     
                     }
                     else
                     {
                        lblFinal.setText("INDICATING HIGH RSIK FOR FAINANCIAL HEALTH");
                     
                     }  
                 
                 }
                 else if("Tailoring Unit"==cmbUnitForPm.getSelectedItem())
                 {
                     
                     float totalMeal=((presentemployee*100)+(presentemployee*150)+(presentemployee*50*20));
                    float productionefficiency=(totalproduction*100)/1500;
                    float damageprecentage=(damagecount*100)/totalproduction;
                    
                    
                     
                     lblMeal.setText("Rs."+totalMeal+ " ");
                     lblProductionEfficiency1.setText(productionefficiency+""+"%");
                     lblDamage.setText(damageprecentage+""+"%");
                     
                     if(productionefficiency>=85 && damageprecentage<=10)
                     {
                     
                        lblFinal.setText("GREAT");
                     
                     }
                     else if(productionefficiency<85 && productionefficiency>=65 && damageprecentage>10 && damageprecentage<=20)
                     {
                        lblFinal.setText("GOOD");
                     
                     }
                     else
                     {
                        lblFinal.setText("INDICATING HIGH RSIK FOR FAINANCIAL HEALTH");
                     
                     } 
                 
                 }
                 else if("Complete Unit"==cmbUnitForPm.getSelectedItem())
                 {
                    float totalMeal=((presentemployee*100)+(presentemployee*150)+(presentemployee*50*20));
                    float productionefficiency=(totalproduction*100)/1500;
                    float damageprecentage=(damagecount*100)/totalproduction;
                    
                    
                     
                     lblMeal.setText("Rs."+totalMeal+ " ");
                     lblProductionEfficiency1.setText(productionefficiency+""+"%");
                     lblDamage.setText(damageprecentage+""+"%");
                     
                     if(productionefficiency>=85 && damageprecentage<=10)
                     {
                     
                        lblFinal.setText("GREAT");
                     
                     }
                     else if(productionefficiency<85 && productionefficiency>=65 && damageprecentage>10 && damageprecentage<=20)
                     {
                        lblFinal.setText("GOOD");
                     
                     }
                     else
                     {
                        lblFinal.setText("INDICATING HIGH RSIK FOR FAINANCIAL HEALTH");
                     
                     } 
                 
                 
                 }
               
            
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.toString());
        }
    }//GEN-LAST:event_btnPmShowActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         SimpleDateFormat sdf;
         sdf = new SimpleDateFormat("yyyy-MM-dd");
        String date=sdf.format(dateForPm.getDate());
        System.out.println(date);
        String unit=(String) cmbUnitForPm.getSelectedItem();
        String e=lblProductionEfficiency1.getText();
        String d=lblDamage.getText();
        String m=lblMeal.getText();
        String f=lblFinal.getText();
        
        try {
             FileWriter objwrite=new FileWriter("Production Report");
             objwrite.write("Production Report");
             objwrite.write("\n");
             objwrite.write("///////////////////////////////////////");
             objwrite.write("\n");
             objwrite.write("Date: "+date);
             objwrite.write("\n");
             objwrite.write("Unit Name: "+unit);
             objwrite.write("\n");
             objwrite.write("Production Efficiency: "+e);
             objwrite.write("\n");
             objwrite.write("Damage Precentage: "+d);
             objwrite.write("\n");
             objwrite.write("Meal Expences: "+m);
             objwrite.write("\n");
             objwrite.write("Final Status: "+f);
             objwrite.write("\n");
             objwrite.close();
             JOptionPane.showMessageDialog(null,"Report is Generated");
         } catch (IOException ex) {
             Logger.getLogger(ProductionManagerPlatForm.class.getName()).log(Level.SEVERE, null, ex);
         }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductionManagerPlatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductionManagerPlatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductionManagerPlatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductionManagerPlatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductionManagerPlatForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableForPm;
    private javax.swing.JButton btnPmShow;
    private javax.swing.JButton btnPmView;
    private javax.swing.JComboBox<String> cmbUnitForPm;
    private com.toedter.calendar.JDateChooser dateForPm;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDamage;
    private javax.swing.JLabel lblFinal;
    private javax.swing.JLabel lblMeal;
    private javax.swing.JLabel lblProductionEfficiency1;
    // End of variables declaration//GEN-END:variables
}
