/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xyz;

import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author USER-PC
 */
public class productionmanagerlog extends javax.swing.JFrame {

    /**
     * Creates new form productionmanagerlog
     */
    public Connection conn=null;
    public Statement stmt=null;
    public  String sql="";
    public productionmanagerlog() {
        initComponents();
        this.setLocationRelativeTo(null);//jframe center
        conn=dbconnection.getConnection();
        
     
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtpmid = new javax.swing.JTextField();
        btnpmclear = new javax.swing.JButton();
        lblpmforget = new javax.swing.JLabel();
        txtpmpassword = new javax.swing.JPasswordField();
        btnpmlog1 = new javax.swing.JButton();
        btnpmback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 600));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("Password");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setText("User Id");

        btnpmclear.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnpmclear.setForeground(new java.awt.Color(0, 0, 102));
        btnpmclear.setText("Clear");
        btnpmclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpmclearActionPerformed(evt);
            }
        });

        lblpmforget.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblpmforget.setForeground(new java.awt.Color(204, 0, 0));
        lblpmforget.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblpmforget.setText("forget password");
        lblpmforget.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblpmforgetMousePressed(evt);
            }
        });

        btnpmlog1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnpmlog1.setForeground(new java.awt.Color(0, 0, 102));
        btnpmlog1.setText("Loging");
        btnpmlog1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpmlog1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtpmid, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtpmpassword))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(btnpmlog1)
                                .addGap(28, 28, 28)
                                .addComponent(btnpmclear, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblpmforget, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpmid, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpmpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnpmclear, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpmlog1))
                .addGap(90, 90, 90)
                .addComponent(lblpmforget, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        btnpmback.setBackground(new java.awt.Color(255, 255, 255));
        btnpmback.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnpmback.setForeground(new java.awt.Color(0, 0, 102));
        btnpmback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/xyz/back.png"))); // NOI18N
        btnpmback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpmbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnpmback, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(232, 232, 232)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(348, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnpmback, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnpmclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpmclearActionPerformed
        txtpmid.setText("");
        txtpmpassword.setText("");
    }//GEN-LAST:event_btnpmclearActionPerformed

    private void btnpmbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpmbackActionPerformed
        productionmanagerlog obj=new productionmanagerlog();
        obj.setVisible(false);
        loging logobj=new loging();
        this.setVisible(false);
        logobj.setVisible(true);
    }//GEN-LAST:event_btnpmbackActionPerformed

    private void lblpmforgetMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblpmforgetMousePressed
        pm_forgot_pass obj=new pm_forgot_pass();
        this.setVisible(false);
        obj.setVisible(true);
    }//GEN-LAST:event_lblpmforgetMousePressed

    private void btnpmlog1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpmlog1ActionPerformed
        if("".equals(txtpmid.getText()) || "".equals(txtpmpassword.getText()))
        {
            JOptionPane.showMessageDialog(null,"Please Enter User Id And Password");
        
        }
        else
        {
        
            try {
                stmt=conn.createStatement();
                
                sql="select*from productionmanager where id='"+txtpmid.getText()+"'";
                ResultSet rs=stmt.executeQuery(sql);
                while(rs.next())
                {
                   String a=rs.getString("id");
                   String b=rs.getString("name");
                   String c=rs.getString("password");
                   String d=rs.getString("age");
                   String pass=c;
                   
                    System.out.println(c);
                    System.out.println(a);
                    
                   
                   
                   if((a == null ? txtpmid.getText() == null : a.equals(txtpmid.getText()))||(c == null ? txtpmpassword.getText() == null : c.equals(txtpmpassword.getText())))
                   {
                     JOptionPane.showMessageDialog(null,"you are in");
                     ProductionManagerPlatForm obj=new ProductionManagerPlatForm();
                     this.setVisible(false);
                     obj.setVisible(true);
                   
                   }
                   else
                   {
                     JOptionPane.showMessageDialog(null, "Invalid User Nmae Or Password");
                   
                   }
                   
                   
                   
                }
                
               
               
                    
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.toString());
            }
        
        
        }
    }//GEN-LAST:event_btnpmlog1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(productionmanagerlog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(productionmanagerlog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(productionmanagerlog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(productionmanagerlog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new productionmanagerlog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnpmback;
    private javax.swing.JButton btnpmclear;
    private javax.swing.JButton btnpmlog1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblpmforget;
    private javax.swing.JTextField txtpmid;
    private javax.swing.JPasswordField txtpmpassword;
    // End of variables declaration//GEN-END:variables
}
